base:
  project: Deep Learning using MlOPS

data_source:
  data_src: ..\Data_Set

load_data:
  num_classes: 3
  raw_data: ..\Data_Set
  preprocessed_data: ..\data\preprocessed
  full_p: \MlOPS-DeepLearning\Data_Set

train_split:
  split_ratio: 80

model:
  name: VGG19
  trainable: False
  train_path: data\preprocessed\train
  test_path: data\preprocessed\test
  image_size: [225,225]
  loss: 'categorical_crossentropy'
  optimizer: 'adam' 
  metrics: ['accuracy']
  epochs: 8
  sav_dir : 'saved_models/trained.h5'


img_augment:
  rescale: 1./255,
  shear_range: 0.2
  zoom_range: 0.2
  horizontal_flip: True
  vertical_flip: True
  batch_size: 18
  class_mode: 'categorical'

  


  